### ISSUE TITLE
Set innodb_flush_log_at_trx_commit to 1 for durability and consistency?

### ISSUE THREAD

**Issue by ghost** [theasci/docker-mysql#1]
Sorry for opening the issue here. The issue is disabled at docker-mysql-tmpfs.
In the mysql [config file](https://github.com/theasci/docker-mysql-tmpfs/blob/master/tmpfs.cnf), **innodb_flush_log_at_trx_commit** is set to 2. 

However, the MySQL [official document](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_flush_log_at_trx_commit) recommends to set it to 1, which helps keep InnoDB ACID Compliant.
"For durability and consistency in a replication setup that uses InnoDB with transactions: **Always set innodb_flush_log_at_trx_commit=1.** ".  

Do you change that to 2 for better performance?

I wonder if there is any durability or consistency concern. Thanks.

**Comment by shawnpyle** [comment]
@HCHCHH, the developer who originally created this is no longer with the company so I can only speculate as to why innodb_flush_log_at_trx_commit=2. It was likely for performance since we only use this in testing our applications, not in production. Seems like you're right, though, if you're using it for something that is data sensative, you'd want innodb_flush_log_at_trx_commit=1. We just don't use it that way.
